version: 0.2

env:
  parameter-store:
    DockerUsername: /myflaskapp/docker-credentials/username
    DockerPassword: /myflaskapp/docker-credentials/password
    DockerURL: /myflaskapp/docker-url
     
phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Installing Dependencies"
      - pip install -r Requirements.txt
  build:
    commands:
      - echo "Building Docker Image"
      - echo "$DockerPassword" | docker login -u "$DockerUsername" --password-stdin 
      - docker build -t "$DockerUsername/simple-flask-app:latest" .
      - docker push "$DockerUsername/simple-flask-app:latest"
      - dir dist
  post_build:
    commands:
      - echo "Build Successful"
artifacts:
  files:
    - dist/abhi1.jar